### ISSUE TITLE
Fehler in der aktuellen Version

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/aufgaben#103]
@skerbis @chrison94 

`Notice: Undefined variable: expand_query in /Users/xxx/Sites/bootstrap4/redaxo/src/addons/aufgaben/pages/aufgaben.php on line 30
Notice: Undefined variable: expand_query in /Users/xxx/Sites/bootstrap4/redaxo/src/addons/aufgaben/pages/aufgaben.php on line 32
Warning: Field "versendet" does not exist in result! in /Users/xxx/Sites/bootstrap4/redaxo/src/core/lib/sql/sql.php on line 620`

Ich hab gar nicht wirklich geguckt...

- Versionsnummer geändert?
- Changelog berücksichtigt?
- Ist ein Update (später im Installer möglich)

LG
Oliver

**Comment by skerbis** [comment]
@olien 
zu Punkt 1: Korrigiert
zu Punkt 2: Versionsnummer auf 4.1.0b gesetzt
zu Punkt 3: Changelog aktualisiert
zu Punkt 4: Sollte funktionieren.

**Comment by olien** [comment]
Super. Danke
