### ISSUE TITLE
Fehler wenn keine E-Mail Adressen eingetragen sind

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/aufgaben#104]
@skerbis @chrison94

Wenn ich eine Aufgabe anlege und keine E-MAil Adresse eingetragen ist erhalte ich folgenden Feh
ler:

![aufgabenfehler](https://user-images.githubusercontent.com/330516/30259983-d6f735b2-96c4-11e7-8074-3395f334dcdc.png)

**Comment by chrison94** [comment]
@olien 

Wann genau tritt der Fehler auf? 

getestet:

Wenn Empfänger leer sind, wird eine neue Aufgabe angelegt mit der Meldung "Keine E-Mail wurde versendet"

Wenn Absender leer ist, übernimmt der PHPMailer und sendet die E-Mail mit der dort hinterlegten Mail-Adresse

Wenn Absender leer ist im PHPMailer, wird keine E-Mail versendet. Die Fehlermeldung tritt bei mir nicht auf. 

Grüße

**Comment by olien** [comment]
hm. ich habe das AddOn installiert (neu) und eine Aufgabe angelegt. Schwups kam der Fehler

**Comment by skerbis** [comment]
Hast du es in einem frischen REDAXO installiert, oder war da schon vorher ein Aufgaben-Addon?
Das Update erstellt die fehlende Spalte, wenn du neu installierst bitte auf reinstallieren klicken, sonst müssen wir es noch mal über den Installer testen und als Beta veröffentlichen.

**Comment by olien** [comment]
Hm. jetzt habe ich ein neues redaxo und das addon von github genommen.
habe eine kategorie angelegt und nach dem anlegen einer aufgabe (funktioniert) kommen folgende meldungen:

`Notice: Use of undefined constant aufgaben - assumed 'aufgaben' in /Users/xx/Sites/xx/redaxo/src/addons/aufgaben/lib/aufgaben_functions.php on line 131
"1"
Notice: Use of undefined constant aufgaben - assumed 'aufgaben' in /Users/xx/Sites/xx/redaxo/src/addons/aufgaben/lib/aufgaben_functions.php on line 154
Notice: Use of undefined constant aufgaben - assumed 'aufgaben' in /Users/xx/Sites/xx/redaxo/src/addons/aufgaben/lib/aufgaben_functions.php on line 155
Notice: Use of undefined constant aufgaben - assumed 'aufgaben' in /Users/xx/Sites/xx/redaxo/src/addons/aufgaben/lib/aufgaben_functions.php on line 156`

**Comment by skerbis** [comment]
@chrison94 bitte fixen

**Comment by chrison94** [comment]
Notice beseitigt - Danke!
