### ISSUE TITLE
Beispieldaten nicht mehr importierbar

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/aufgaben#105]
@skerbis @chrison94

Der Importlink findet sich unter "Info" (letzter Link).

LG
Oliver

**Comment by chrison94** [comment]
Sollte wieder klappen - Danke!

**Comment by olien** [comment]
Die Kategorien werden importiert. Die Aufgaben landen zwar in der Datenbank werden aber nicht ausgegeben.

**Comment by skerbis** [comment]
Hat sich durch die Umstellung login/name eingeschlichen. Problem bestand also schon früher, ist korrigiert: https://github.com/FriendsOfREDAXO/aufgaben/commit/395d522631979948dfc9e8b3852f3eb551270cc1
