### ISSUE TITLE
Fehler in den Einstellungen

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/aufgaben#106]
Aufgaben werden nicht angezeigt.

Hängt wahrscheinlich hiermit zusammen:

![aufgaben](https://user-images.githubusercontent.com/330516/30275885-3ad0aed6-9703-11e7-8220-d68d062198d9.png)

Sorry  @chrison94 :-)

**Comment by chrison94** [comment]
Meinst du dass man die 2 Ansichten nicht direkt am Anfang sieht oder geht es um die Warning?

**Comment by olien** [comment]
Naja. Es wird halt keine Ansicht (als Tab) angezeigt.
Es funktioniert erst wenn ich eine Ansicht (oder beide) auswähle und die Einstellungen speichere...

**Comment by chrison94** [comment]
Wurde behoben, danke!
