### ISSUE TITLE
Debug Ausgabe + "Es wurde keine E-Mail versendet"

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/aufgaben#107]
Diese Ausgabe erscheint sehr oft beim anlegen einer neuen Aufgabe (Einstellungen Mailtechnisch nicht angefasst. :-)

![unbenannt-1](https://user-images.githubusercontent.com/330516/30278330-674986f2-970a-11e7-842f-a6f3c012d463.png)

**Comment by chrison94** [comment]
Da ist mir wohl ein Dump durch die Finger gerutscht :-)
Die vielen Meldungen sollten jetzt auch nicht mehr auftreten.
