### ISSUE TITLE
Noch eine Notice und eine Debug Ausgabe

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/aufgaben#108]
Aktuelle Github Version. Frisch installiert.
Meldungen kommen beim Mailversand.

![aufgaben](https://user-images.githubusercontent.com/330516/30312639-ab3da48e-979a-11e7-90e2-110eb83dfd8d.png)

**Comment by chrison94** [comment]
Notice sollte behoben sein - sehe die bei mir nicht.
dump ist weg. sorry :-)
