### ISSUE TITLE
Zeitversetztes senden der E-Mails funktioniert bei mir nicht

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/aufgaben#111]
"Ohne Verzögerung" funktioniert.

Auch wenn ich zeitversetztes senden eingeschaltet habe (5 Minuten), einige Aufgaben änder und neu anlege, 30 Minuten warte (bisschen im Backend rumklicke) wird nix gesendet. Stelle ich dann auf "Ohne Verzögerung" um, änder etwas bekomme ich per Mail alle Änderungen....

**Comment by skerbis** [comment]
@olien das ganze spielt sich aktuell nur in der aufgaben.php ab. Es müsste alles noch in die boot.php bzw. in eine eigene Funktion ausgelagert werden.  Es ist jetzt erstmal da und dann schauen wir mal weiter.

**Comment by olien** [comment]
Ok. Wusste ich nicht. Danke für die Antwort

**Comment by skerbis** [comment]
Also es wird nur ausgelöst, sollten Änderungen durchgeführt werden.

**Comment by olien** [comment]
Sollte jetzt ok sein - so wie es ist.
