### ISSUE TITLE
Was bedeutet das E-Mail Symbol in der Listenansicht

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/aufgaben#117]
Habe noch nicht rausgefunden wann das genau angezeigt wird und was es bedeutet.

Mail zu der Aufgabe wurde (oder wird noch) verschickt??
Ist es eine wichtige Info, die mit in die Tabelle muß?

LG
Oliver

**Comment by skerbis** [comment]
Wenn zum aktuellen Stand eine Email verschickt wurde, wird es angezeigt

**Comment by olien** [comment]
Die Info hat doch nur einen Wert nachdem zum erstmal eine Änderung (E-Mail verschickt) gemacht wurde. Danach ist das symbol aussagelos - oder? So wie das Addon nutze werden Aufgaben im laufe des Projektes ja öfter geändert...

**Comment by skerbis** [comment]
Wenn du es änderst ist da auch erstmal kein E-Mail-Symbol. Erst wenn die Änderung verschickt wurde. (sollte eigentlich so sein)

**Comment by olien** [comment]
wenn ich etwas ändere und eine e-mail gesendet wurde kommt das symbol.
das bleibt aber da. wenn ich mich wieder einlogge ist das symbol noch da.
wenn ich dann nochmal diese aufgabe ändere ändert sich nichts, da das symbol ja schon da ist. somit hat es keinen mehrwert - oder?

**Comment by skerbis** [comment]
Dann ist's buggy …Vielleicht sollten wir uns zu dem AddOn noch mal zusammensetzen?

**Comment by olien** [comment]
mal sehen ob sich das lohnt. für mich reicht es :-))
ich mache hier erst einmal zu
