### ISSUE TITLE
„Aufgaben“ werden nicht angezeigt 

### ISSUE THREAD

**Issue by Geri2017** [FriendsOfREDAXO/aufgaben#119]
Neue Aufgaben anlegen nicht möglich, da kein Feld vorhanden. 
In der DB existiert das Feld. 
![A2DCB1D8-B1D8-467F-A060-56A1788BF9A3](https://user-images.githubusercontent.com/45007596/70388221-175a8180-19af-11ea-9b17-ab1761f1a4fa.png)
![1973509F-8669-46FC-9E32-428A7F0D8B41](https://user-images.githubusercontent.com/45007596/70388236-4d980100-19af-11ea-8e00-31892c84a698.jpeg)

**Comment by olien** [comment]
Hm. Kannst du mal unter Info die Beispielaufgaben installieren (ganz unten).

**Comment by Geri2017** [comment]
Nach Beispieldaten:
![Bildschirmfoto 2019-12-08 um 16 14 32](https://user-images.githubusercontent.com/45007596/70391473-fa857480-19d5-11ea-9672-318e65eccc23.png)
![Bildschirmfoto 2019-12-08 um 16 14 41](https://user-images.githubusercontent.com/45007596/70391474-fce7ce80-19d5-11ea-985f-d379dc5ded11.png)
Daten vorhanden, aber kein Button :-(

**Comment by olien** [comment]
Muss ich morgen gucken. Hast du das mal bei einer anderen Installation ausprobiert oder die Ansicht unter Einstellungen geändert?

**Comment by olien** [comment]
Ich habe Aufgaben jetzt in einer frischen REDAXO Installation installiert. Problemlos. Vielleicht magst DU mir mal einen Zugang zu Deiner Seite geben?
