### ISSUE TITLE
Fehlermeldung nach Installation 

### ISSUE THREAD

**Issue by dzinedev** [FriendsOfREDAXO/aufgaben#125]
Ich habe das Addon installiert und beim Aufruf der Seite bekomme ich folgenden Fehler:
```
rex_sql_exception thrown with message "Error while executing statement "SELECT SQL_CALC_FOUND_ROWS a.*,
                   a.id AS id,
                   k.id,
                   k.category AS category_name,
                   k.color, u.name AS realname 
                   FROM rex_aufgaben AS a, rex_aufgaben_categories AS k, rex_user AS u WHERE  a.status > 0 and a.category = k.id and a.createuser = u.login  GROUP BY a.id ORDER BY a.id DESC LIMIT 0,30"! SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) for operation '='"
```
Was kann ich da tun?

**Comment by olien** [comment]
Hallo, 

leider kann ich den Fehler nicht nachvollziehen. Habe gerade das AddOn problemlos installiert. Kannst Du mal gucken ob die Installation auf einer anderen Webseite funktioniert?

LG
Oliver

**Comment by dzinedev** [comment]
Hey, hab´s schon gelöst. Das Redaxo existiert schon eine ganze Weile. Habe den Zeichensatz bei der rex_user Tabelle überall von utf8_general_ci auf utf8_unicode_ci geändert. Nun läufts :)

**Comment by olien** [comment]
Super. Dann kann das ja hier zu...
