### ISSUE TITLE
Error nach installation - mysql

### ISSUE THREAD

**Issue by steri-rex** [FriendsOfREDAXO/aufgaben#126]
Nach der Installation von v. 4.1.3. kommt diese fehlermeldung (REDAXO | 5.11.0 - MariaDB 5.5.68)
`Error while executing statement "SELECT SQL_CALC_FOUND_ROWS a.*, a.id AS id, k.id, k.category AS category_name, k.color, u.name AS realname FROM rex_aufgaben AS a, rex_aufgaben_categories AS k, rex_user AS u WHERE a.status > 0 and a.category = k.id and a.createuser = u.login GROUP BY a.id ORDER BY a.id DESC LIMIT 0,30"! SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) for operation '='`

**Comment by pschuchmann** [comment]
Gerade im Slack gelöst:
![image](https://user-images.githubusercontent.com/35096518/106358183-c0c6aa00-630a-11eb-892e-fd550746d3f9.png)

**Comment by steri-rex** [comment]
danke - kollation von allen tabellen "rex_aufgaben... " auf utf8_general_ci ändern - hat funktioniert

**Comment by olien** [comment]
was muß denn hier geändert werden? (Install.php)

```
rex_sql_table::get(rex::getTable('aufgaben'))
    ->ensurePrimaryIdColumn()
    ->ensureColumn(new rex_sql_column('title', 'varchar(255)', true))
    ->ensureColumn(new rex_sql_column('description', 'longtext', true))
    ->ensureColumn(new rex_sql_column('category', 'int(10)', true))
    ->ensureColumn(new rex_sql_column('responsible', 'int(10)', true))
    ->ensureColumn(new rex_sql_column('prio', 'int(10)', true))
    ->ensureColumn(new rex_sql_column('status', 'int(10)', true))
    ->ensureColumn(new rex_sql_column('createdate', 'datetime', true))
    ->ensureColumn(new rex_sql_column('updatedate', 'datetime', true))
    ->ensureColumn(new rex_sql_column('createuser', 'varchar(255)', true))
    ->ensureColumn(new rex_sql_column('updateuser', 'varchar(255)', true))
    ->ensureColumn(new rex_sql_column('observer', 'varchar(255)', true))
    ->ensureColumn(new rex_sql_column('finaldate', 'varchar(255)', true))
    ->ensureColumn(new rex_sql_column('versendet', 'varchar(255)', true, '2'))
    ->ensure();


rex_sql_table::get(rex::getTable('aufgaben_categories'))
    ->ensurePrimaryIdColumn()
    ->ensureColumn(new rex_sql_column('category', 'varchar(255)', true))
    ->ensureColumn(new rex_sql_column('color', 'varchar(255)', true))
    ->ensure();


rex_sql_table::get(rex::getTable('aufgaben_filter'))
    ->ensurePrimaryIdColumn()
    ->ensureColumn(new rex_sql_column('user', 'varchar(255)', true))
    ->ensureColumn(new rex_sql_column('category', 'varchar(255)', true))
    ->ensureColumn(new rex_sql_column('responsible', 'varchar(255)', true))
    ->ensureColumn(new rex_sql_column('prio', 'varchar(255)', true))
    ->ensureColumn(new rex_sql_column('status', 'varchar(255)', true))
    ->ensureColumn(new rex_sql_column('done', 'varchar(255)', true))
    ->ensure();

rex_sql_table::get(rex::getTable('aufgaben_status'))
    ->ensurePrimaryIdColumn()
    ->ensureColumn(new rex_sql_column('status', 'varchar(255)', true))
    ->ensureColumn(new rex_sql_column('icon', 'varchar(255)', true))
    ->ensure();

rex_sql_table::get(rex::getTable('aufgaben_user_settings'))
    ->ensurePrimaryIdColumn()
    ->ensureColumn(new rex_sql_column('user', 'int(10)', true))
    ->ensureColumn(new rex_sql_column('counter', 'int(10)', true))
    ->ensure();
```
    
    ich kann das in meinen aktuellen REDAXO Installationen fehlerfrei installieren...

**Comment by pschuchmann** [comment]
@olien ich fürchte fast, dass es nicht der Code ist. Kannst du bitte mal schauen mit welcher Kollation deine Tabellen angelegt wurden? Bzw. mit welcher eine frisch angelegte Tabelle erstellt wird und @steri-rex bitte auch? Vielleicht liegt das Problem im Default der Datenbank und nicht im Addon. Aber ist nur eine Vermutung.

**Comment by olien** [comment]
Also ich habe jetzt redaxo 2x installiert: einmal mit utf8mb4 und einmal mit utf8 [deprecated]. 

Mit beiden Versionen hatte ich bei der Installation und dem anlegen, bearbeiten und löschen von Aufgaben keine Probleme.
