### ISSUE TITLE
Einzelnen Aufgaben/Kategorien nur für Admins definierbar machen

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/aufgaben#128]
Möglichkeit schaffen, um einzelnen Aufgaben und/oder Kategorien nur für Admins sichtbar zu machen und vor "normalen" User zu verbergen.

**Comment by olien** [comment]
Oh. Das AddOn ist so alt. Bist vielleicht der einzige der das noch nutzt oder? Magst du es übernehmen?

**Comment by iceman-fx** [comment]
Genutzt habe ich es noch nicht, wollte es aber mal.
Lässt sich aber nicht installieren wegen falschen Abhängigkeiten.

Wenn ich mal Zeit habe, kann ich es gern mal etwas versuchen anzupassen.
