### ISSUE TITLE
DB Felder umbenennen

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/aufgaben#15]
aufgaben
- id
- kategorie_id
- titel

kategorien
- id
- name

**Comment by phoebusryan** [comment]
(optional) Nenne doch auch noch die Tabellen um in Tasks und Categories.. dann wärs direkt international ;)

**Comment by olien** [comment]
beim nächsten Addon gerne

**Comment by olien** [comment]
Lasse ich jetzt so...
