### ISSUE TITLE
Idee: neues UI

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/aufgaben#21]
okay, also ich weiss wie ich es machen würde. die aufgaben-liste würde ich ganz nach oben schieben und die tabs entfernen. über der liste eine box mit ebenfalls grauem border und weissem bg und da drin filter. dann kannst du die in der kopfzeile wieder entfernen.

die option "erledige anzeigen" würde ich ebenfalls da oben in die box reinnehmen als konfiguration. somit fällt die spalte rechts weg. die edit-icons würde ich entsprechend nach links nehmen anstelle der kalender-icons (die sind unnötig)

**Comment by phoebusryan** [comment]
Vergiss das oben; es ist Quatsch.

Die obere box kannst du weglassen und dafür in der Kopfzeile neben den jeweiligen Spalten ein Plus oder ein Filtericon oder ähnliches machen. Ein Klick darauf öffnet ein Dropdown mit Checkboxen drin, wo man mehrere anhaken kann. Ich hab das Addon jetzt gestern und heute intensiv genutzt und es ist aus meiner Sicht essentiell, dass man auch nur einzelne Kategorien ausblenden kann. Zum Beispiel wenn man 7 hat aber nur 5 relevant sind im Moment.

Das Auge würde ich dann rechts neben der Kopfzeile "Aufgaben" hinsetzen.

Das Kalendericon trotzdem durch das Editicon ersetzen und die letzte Spalte entfernen.

Den Tab "Info" würde ich komplett in die help.php integrieren und den Tab dann entfernen.

Den Tab "Kategorien" würde ich vorerst lassen. Da fällt mir gerade nichts passendes ein.

---

Jep, das ergibt Sinn so.

**Comment by phoebusryan** [comment]
Folgendes fehlt noch:

"Die obere box kannst du weglassen und dafür in der Kopfzeile neben den jeweiligen Spalten ein Plus oder ein Filtericon oder ähnliches machen. Ein Klick darauf öffnet ein Dropdown mit Checkboxen drin, wo man mehrere anhaken kann. Ich hab das Addon jetzt gestern und heute intensiv genutzt und es ist aus meiner Sicht essentiell, dass man auch nur einzelne Kategorien ausblenden kann. Zum Beispiel wenn man 7 hat aber nur 5 relevant sind im Moment."

**Comment by olien** [comment]
Ist erledigt und - hoffentlich bald - auch online :-)

**Comment by phoebusryan** [comment]
Top! Freue mich drauf.
