### ISSUE TITLE
Nicht zugewiesene Optionen werden im Filter angezeigt

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/aufgaben#22]
Bsp. Kategorien. Nach den Import der Demodaten sind nur 2 Kategorien (Seo, Grundlagen) zugewiesen. Im Filter erscheinen aber alle Kategorien. Ist auch bei den anderen Filtern so.

**Comment by phoebusryan** [comment]
Fix ist drin, kann somit geschlossen werden.

@olien Haust du Version 1.7.2 raus?

**Comment by olien** [comment]
Cool.Danke. Ist draußen
