### ISSUE TITLE
Zähler in der Navigation

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/aufgaben#23]
Ein Zähler zu offenen Tonics in der Navi wäre cool.

**Comment by olien** [comment]
Coole Idee!
Unter Berücksichtigung der eingestellten Filter natürlich - oder? :-)

**Comment by skerbis** [comment]
Soweit habe ich nicht gedacht. hört sich aber toll an

**Comment by olien** [comment]
Ist erledigt...
