### ISSUE TITLE
Warnings und Umgang mit install und update

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/aufgaben#26]
Habe immer wieder warnings, weil irgendwelche Felder fehlen.

Ich würde das in der install.php und update.php an deiner Stelle ergänzen.
Und zwar hat REDAXO Hilfsmittel dafür, so dass man sicher sein kann,
dass die Felder up to date sind.

Ein Beispiel.

```
rex_sql_table::get("rex_aufgaben_kategorien")
->ensureColumn(new rex_sql_column('yrewrite_url', 'varchar(255)'))
->ensureColumn(new rex_sql_column('yrewrite_canonical_url', 'varchar(255)'))
->alter();
```

und wenn das in den genannten Dateien drin ist, kann man sicher sein,
dann bei einem Reinstal oder Update wieder alles klappt ..

lg

**Comment by olien** [comment]
Ich gucke es mir an sobald ich mit dieser anderen Sache fertig bin :-) Danke!

**Comment by olien** [comment]
Ist geändert. Evtl. könntest du mal einen Blick drauf werfen?
(nur die github Version)

**Comment by olien** [comment]
Sollte funktionieren
