### ISSUE TITLE
Richtige Beispieldaten einfügen

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/aufgaben#3]

**Comment by phoebusryan** [comment]
Wofür Beispieldaten? Das AddOn ist ziemlich inutitiv. Man könnte den Tab 'Info' meiner Meinung nach ganz entfernen. :-)

**Comment by olien** [comment]
Ich würde gerne die Standardaufgaben - die bei der Entwicklung einer Seite benötigt werden einfügen...

**Comment by eaCe** [comment]
Hierzu könntest du dir das eigentlich bei webdevchecklist abschauen

**Comment by skerbis** [comment]
das wird wohl nix. Wieder aufmachen, falls von Interesse
