### ISSUE TITLE
Import / Export von Aufgaben

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/aufgaben#34]

**Comment by eaCe** [comment]
Würde dir helfen falls ich das hinbekomme, in welcher Form magst du den Im/Export haben?

**Comment by olien** [comment]
Das wäre total klasse. Format wäre mir egal. Ich hätte mich an dem Backup Addon orientiert...

**Comment by eaCe** [comment]
Ok, werde mich am Wochenende mal der Sache annehmen

**Comment by olien** [comment]
Freu mich!.

Bei dem Import müsstest du evtl. die Felder eigentuemer, creaetuser, updateuser mit der rex_user  Tabelle abgleichen (id, login, login).

LG
Oliver

**Comment by tbaddade** [comment]
> in welcher Form magst du den Im/Export haben?

Bei einem Aufgabentool, wäre .sql als Backup und .csv als Import für Sheets sehr sinnvoll.

**Comment by eaCe** [comment]
.csv hätte ich durch json ersetzt, kann das aber auch so machen. am ende kann man ja auch beides anbieten :)

**Comment by olien** [comment]
dann sollten wir auch eine beschreibung liefern wie das csv auszusehen hat.
(und evtl. teilweise leere felder zulassen bzw automatisch füllen ..)

das wär cool. ich dachte nur daran "eigen" daten zu importieren aber so wäre es viel felxibler...

**Comment by eaCe** [comment]
Ich habe am Wochenende mal ausprobiert und würde aber beides dann auf CSV basis machen.
Warum sollten wir beim Export SQL nutzen? Es geht ja nicht um ein Backup im klassischem Sinne, ich würde eine CSV zum Download anbieten.

**Comment by olien** [comment]
Super. Für mich ist CSV vollkommen ok!

**Comment by olien** [comment]
Machst Du ne eigene Import/Exprot Seite zwischen Kategorien / Info - nur für Admins??

**Comment by eaCe** [comment]
Eine eigene Seite habe ich angelegt, nur für Admins noch nicht, kann ich aber berücksichtigen. Ergibt ja auch Sinn :)

**Comment by olien** [comment]
Ideen... 
Export direkt zu Excel (https://phpexcel.codeplex.com)
Export mit Filter (Prio, Status, Zuständig...)

**Comment by olien** [comment]
Änderungen getestet. **Super**!

Toll wäre es noch wenn ich wählen könnte zwischen "Aktuelle Filtereinstellungen" / "Alle Aufgaben" und
wenn in den Feldern "Kategorie,Eigentümer,Prio,Status' nicht die ID sondern die Bezeichnung stehen würde...

**Comment by olien** [comment]
Den Export habe ich gerade geschossen... :-( Sorry
