### ISSUE TITLE
E-Mail bei Änderung von Status, Prio und vor allen Dingen beim löschen einer Aufgabe

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/aufgaben#36]

**Comment by skerbis** [comment]
Hmmm .... ist das schon integriert. Es scheinen keine Mails verschickt zu werden.

**Comment by olien** [comment]
Für die genannten Punkte ist es noch nicht integriert. Zumindest nicht von mir :-)

Bein anlegen/ändern sollte was gesendet werden.
Hat der betreffende User eine E-Mail Adresse?

LG
Oliver

**Comment by skerbis** [comment]
Ok. Anlegen/Ändern klappt. 👍 (grrr. blöder SPF-Check auf Mailserver war schuld)
