### ISSUE TITLE
Anpinnen von Aufgaben an "irgendeine" Stelle

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/aufgaben#43]
angenommen ich bin in der Struktur in irgendeiner Kategorie
oder im Medienpool in einem Medium
oder in einem spezielle Artikel
...

und dort mit einem "+ Todo" einen ToDo reinhängen, so dass ich von der Übersicht direkt dahin komme, oder dieses Todo halt auftaucht, wenn ich diesem Bereich bin.

Wäre ziemlich praktisch. Hat dann immer einen direkten REDAXO Bezug (Bereich und oder Datensatz).

Gerade auch für Redakteure. Z.B. in der YForm in einer Tabelle bei einem speziellen Datensatz eine Todo drankleben und im Aufgaben AddOn das gelistet bekommen...

**Comment by olien** [comment]
Wow. Das ist eine super Idee. Kannst du mir einen Ansatz geben wie das realisierbar wäre??
