### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by TrueHatori** [FriendsOfREDAXO/aufgaben#49]
`parse error: failed at``/is/htdocs/wp10477139_MJAUB0YEIY/www/redaxo-test/redaxo/src/addons/be_style/../aufgaben/scss/_pickaday.scss on line 248`

Ich habe bei verschiedenen Installationsversuchen immer andere Fehler :( Hier der vom letzten Versuch.
Seltsamerweise funktioniert es auf der heimischen Festplatte mit XAMPP tadellos.

**Comment by olien** [comment]
Hat das Problem noch jemand?

**Comment by eaCe** [comment]
Habe den Fehler nicht, kannst du mal die _pickaday.scss bei der es knallt hier als code posten? @TrueHatori

**Comment by olien** [comment]
Der Pfad ist

`/redaxo/addons/aufgaben/scss/_pickaday.scss`

**Comment by eaCe** [comment]
@olien ja schon, nur hat er vielleicht irgendeine andere version/irgendein verstecktes zeichen in seiner. Irgendwoher muss der error ja kommen

**Comment by olien** [comment]
Wollt nur einen Tipp geben wo er suchen muss.

Gucke Dir mal den Pfad im ersten Post an...

**Comment by TrueHatori** [comment]
Sorry, ich kann nur die Fehlermeldung ansagen. Was ich aber gerade sehe, da fehlt was in der geposteten Fehlermeldung. Da fehlt ein Hochkomma hinter failed at. Ich nehme an, das hat der Editor hier verschluckt.

/EDIT
Hab es gerade nochmal versucht, nach dem "failed at" sind in der Fehlermeldung noch zwei Back-Ticks, die oben in der geposteten Fehlermeldung aus irgendeinem Grund fehlen.

**Comment by TrueHatori** [comment]
Bin ich wirklich der Einzige, der diesen Fehler hat?

**Comment by eaCe** [comment]
@TrueHatori  ich kann ihn nicht reproduzieren...
Hast du irgendwelche Anpassungen im SCSS gemacht an irgendeiner stelle? 
Alle Addons up to date?

**Comment by TrueHatori** [comment]
Nein, nichts gemacht, soweit komme ich ja gar nicht. Addon über den Installer runterladen, Menüpunkt Addons und installieren, da kommt der Fehler.
Kannst Dir das gern selber angucken und versuchen:
[http://www.ninja4ever.de/redaxo-test/redaxo/](http://www.ninja4ever.de/redaxo-test/redaxo/)
Da gibt es einen User Test-Admin mit Passwort 192837465
Hab nach dem letzten Versuch saubergemacht, sprich, das Addon ist raus und auch die Tabellen sind gelöscht. Einigt Euch nur, wer es probiert, beim Zweiten kommt schon vorher ein Fehler, weil dann die Tabellen noch drin sind.

**Comment by olien** [comment]
Ich vermute mal, dass das hier geschlossen werden kann...
