### ISSUE TITLE
Konfigurationsseite für Users- / Adminsettings

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/aufgaben#53]
- Wunschansicht festlegen (Tabelle / Kanban)
- E-Mail Benachrictigungen ein- / ausstellen
- Aufgaben löschen erlauben / verbieten f. Benutzer

Weitere Ideen gewünscht!

**Comment by olien** [comment]
Auswahl: Tabelle / Kanban ist eingebaut. 
Hier mache ich einen Redirect bei der Einstellungsseite. Das geht schöner...

**Comment by tbaddade** [comment]
> E-Mail Benachrictigungen ein- / ausstellen

macht du diese Einstellung für jeden User oder allgemein gültig?

**Comment by olien** [comment]
Ich dachte an ein Multiselectfeld welches die vorhandenen E-Mail Adressen als Optionen hat...

**Comment by olien** [comment]
Zwei Punkte erledigt: 

Wunschansicht festlegen (Tabelle / Kanban)
E-Mail Benachrictigungen ein- / ausstellen
