### ISSUE TITLE
Kanban responsive machen

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/aufgaben#54]
Ja / Nein?

**Comment by skerbis** [comment]
ja

**Comment by eaCe** [comment]
eigentlich ist es quasi responsive, diese bootstrap modal sache ist ein weit verbreitetes problem...
weil ich den modal im content und nicht am ende einbinde passiert das... der rest sollte im prinzip auch mobil funktionieren

**Comment by olien** [comment]
Nö. Es wird (bei mir) ein Scrollbalken angezeigt...

![kanban](https://cloud.githubusercontent.com/assets/330516/15814148/f59ce5aa-2bc4-11e6-9b80-96704e234e4f.png)

**Comment by eaCe** [comment]
Ja das ist eigentlich auch so gewollt, habt ihr Ideen das anders darzustellen? Einfach untereinander?

**Comment by olien** [comment]
Hm. Hat alles seine Berechtigung... ich würde die container evtl. fluid machen und mit einer Mindestbreite immer so viele darstellen wie es sinnvoll ist..

evtl. ähnlich dem bootstrap grid??

**Comment by olien** [comment]
OK
