### ISSUE TITLE
In der Kanban Ansicht funktioniert das Anlegen einer neuen Aufgabe nicht (Smartphone Darstellung)

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/aufgaben#56]

**Comment by eaCe** [comment]
Ah danke, das ist so ein Bootstap fehler... Wenn du meinst das die form hinter dem layer liegt?
Das kann ich recht schnell fixen

**Comment by olien** [comment]
genau

**Comment by eaCe** [comment]
Sollte im neuen pr gelöst sein, könnte mal jemand außer mir noch testen

**Comment by olien** [comment]
Danke. Funktioniert. 3.1.1. ist im Installer :-)
