### ISSUE TITLE
Kanban Settings anlegen

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/aufgaben#58]
Einstellungen um z.B.:
- Status ein / aus zublenden
- Eigentümer ein / aus zublenden

**Comment by olien** [comment]
Das kann auch gerne in der allgemeinen Einstellungsseite

**Comment by olien** [comment]
Wieder aufmachen falls sich das noch jemand wünscht (und dann direkt umsetzen) :-))
