### ISSUE TITLE
css radiobuttons

### ISSUE THREAD

**Issue by rokitole** [FriendsOfREDAXO/aufgaben#61]
scheint als lässt pikaday im backend radiobuttons verschwinden :)
![bildschirmfoto 2016-06-06 um 14 26 36](https://cloud.githubusercontent.com/assets/11247158/15821893/e735f9ec-2bf2-11e6-8a5e-8a3ab4392156.png)

**Comment by eaCe** [comment]
Oh oh, das bin ich im SCSS vom export.scss, werde es in eine wrapper-klasse werfen, entschuldige die Probleme

**Comment by olien** [comment]
SCSS Datei für die Exportseite ersatzlos entfernt. Ich hoffe das ist OK.
Irgendwann ziehen wie die Optik nochmal komplett "gerade"...
