### ISSUE TITLE
Kanban Ansicht :: helle Kategoriefarbe auf grau nicht lesbar

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/aufgaben#67]
Lege eine Kategorie mit Gelb an. Dann siehst was ich meine.

**Comment by olien** [comment]
Ja. Die Kanban Ansicht möchte ich mit Thorbens Erlaubnis mal optisch überarbeiten :-)

**Comment by olien** [comment]
In Version 4 gefixt
