### ISSUE TITLE
Aufgaben Badge in Hauptnavi wird nicht aktualisiert

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/aufgaben#70]
Legt man eine neue Aufgabe an, bleibt der Zählen stehen. Liegt am pjax

**Comment by olien** [comment]
Hm. Hab jetzt einige Zeit versucht das zu beheben. Hast Du evtl. einen Tipp für mich wie ich das Problem lösen kann?

**Comment by tbaddade** [comment]
Das einfachste wäre, das pjax auf false zu setzen.

Alternativ könntest du dir die Anzahl via Ajax holen und dann mittels js ersetzen.

``` js
$(document).on('rex:ready', function (event, container) {
    // Deine Funktionen
});
```

**Comment by olien** [comment]
Danke... pjax möchte ich gerne auf true lassen.
Den anderen Weg gucke ich mir an.

**Comment by tbaddade** [comment]
Vermutlich nach all der Zeit schon behoben.
