### ISSUE TITLE
interner Link funktioniert nicht

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/aufgaben#74]
Textile Markup

Eingabe
`"siehe hier":redaxo://1`

Der Link wird dargestellt, jedoch ist die Url im Backend verkehrt.
`<a href="redaxo://1">siehe hier</a>`

**Comment by gharlan** [comment]
Was hat das mit dem Aufgaben-Addon zu tun? ;)

**Comment by tbaddade** [comment]
> Was hat das mit dem Aufgaben-Addon zu tun

Da die Links innerhalb der Slices nicht aufgelöst werden (m.E. auch in R4 so), sollten diese zumindest im Aufgaben-Addon korrekt in das Frontend zeigen.

Bestenfalls sogar ein `"siehe hier":backend://1` zeigt auf die Backendseite

**Comment by olien** [comment]
@tbaddade wo schreibst du die Links? In das Beschreibungsfeld?

**Comment by tbaddade** [comment]
> In das Beschreibungsfeld?

ja

**Comment by olien** [comment]
Was könnt ich da machen?
Textile / MarkItUp funktioniert grundsätzlich

Grundsätzlich wäre es doch schön wenn das in Addons funktionieren würde - oder?

**Comment by tbaddade** [comment]
> Grundsätzlich wäre es doch schön wenn das in Addons funktionieren würde - oder?

Gute Frage, wenn die Links auch in den Slices ordentlich sein sollen, gehört das Issue nicht hierher sondern eher in das **Textile AddOn**. Was meinst du @gharlan

**Comment by tbaddade** [comment]
Ich schließe wegen Inaktivität.
