### ISSUE TITLE
Sehr Ressourcenhungrig

### ISSUE THREAD

**Issue by VIEWSION** [FriendsOfREDAXO/aufgaben#78]
Hi,

mein lokales Redaxo / MAMP Setup war auf einmal furchtbar langsam. Vor allem das Backend brauchte mehr als 3 Sekunden für einen Seitenaufruf. Ich habe dann AddOn für AddOn wieder deaktiviert. Sobald "Aufgaben" aus war, ging alles wieder superschnell.
Ich habe jetzt nicht genau untersucht warum das so ist, aber es scheint so als ob es einiges an Ressourcen braucht.... vielleicht kann man da noch das eine oder andere optimieren.

Gruß,
Matthias

**Comment by olien** [comment]
Hallo Matthias,

danke für den Hinweis. Kannst du mal in der package.yml

das 

compile: 1

in 

compile: 0

ändern und gucken ob es besser wird?

LG
Oliver
(Arbeite gerade an einer neuen Version...)

**Comment by olien** [comment]
In Version 4 gefixt
