### ISSUE TITLE
Mail erst senden wenn Aufgabe gespeichert!

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/aufgaben#81]
Aktuell werden Mails beim anlegen / editieren einer Aufgabe auch gesendet sofern das Formular nicht richtig ausgefüllt wurde. Das ist falsch. Allerdings hat das den Vorteil, dass auch Mails gesendet werden sofern eine Aufgabe gelöscht wird.

Wunschverhalten: Mails sollen nur gesendet werden sofern das Formular richtig ausgefüllt und abgeschickt wurde. Die Mails für gelöschte Aufgaben sollen aber trotzdem noch (mit Inhalt) gesendet werden..

Vorghensweise?

```
rex_extension::register('REX_FORM_SAVED', function (rex_extension_point $ep) {
    if (!$ep->getSubject()) {
        return;
    }
    $form = $ep->getParam('form');
    // ...
});

```

**Comment by AWqxKAWERbXo** [comment]
+1

**Comment by skerbis** [comment]
Mails werden in einem festgelegten Zeitintervall versendet. So dass nicht jede Änderung bei den Zuständigen erscheint. -> Die Aufgaben werden je User gesammelt und dann versendet.
