### ISSUE TITLE
Analog Kategorien eigene Status'

### ISSUE THREAD

**Issue by phoebusryan** [FriendsOfREDAXO/aufgaben#9]
Ich benötige ganz andere Status' als vorgegeben. Wäre schön, wenn man diese auch anpassen könnte.

**Comment by phoebusryan** [comment]
Achso, das hängt mit den Buttons in der Liste zusammen. Das müsste man jeweils noch ein Icon definieren pro Status. Praktisch wäre es trotzdem sehr.

**Comment by olien** [comment]
Mal sehen. Lass es mich erst einmal fertig bauen :-))

**Comment by olien** [comment]
Kann ja eigentlich relativ schnell in der install sql angepasst werden...

**Comment by phoebusryan** [comment]
Was hat das mit der install.sql zu tun? das muss eher ins rex_form / rex_list ;)

**Comment by olien** [comment]
Ich meinte nur falls du der einzige mit dem Wunsch sein solltest;-))

**Comment by phoebusryan** [comment]
Achso gemeint. Hm; ja lass es mal bleiben. Ist nicht so wichtig. Und eben; zur not kann ich über die DB ;-)
