### ISSUE TITLE
Fälligkeit korrekt sortieren

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/aufgaben#92]
Wenn man nach Fälligkeit sortiert, werden erst leere Felder ausgegeben - als Nutzer erwartet man aber, dass auf Anhieb die Aufgaben mit der knappsten Fälligkeit ausgegeben werden.

Außerdem kommt das hier bei der Sortierung raus:
![image](https://cloud.githubusercontent.com/assets/3855487/19143777/59edbade-8ba6-11e6-832a-e42e4ed8e7be.png)

Nach Tag zu sortieren ergibt keinen Sinn.

Lösungsmöglichkeit:
https://datatables.net/ (auch mit Bootstrap kompatibel)

**Comment by skerbis** [comment]
@alexplusde Magst ein PR liefern?

**Comment by AWqxKAWERbXo** [comment]
Benutzen das Addon leider nicht mehr

**Comment by skerbis** [comment]
bitte wieder öffnen, falls das Problem noch besteht
