### ISSUE TITLE
eine leere Kategorie 

### ISSUE THREAD

**Issue by mbodon** [FriendsOfREDAXO/aufgaben#97]
Könnte es eine leere Kategorie geben (so wie z.B. im Medienpool) damit nam nicht immer eine Kategorie auswählen muss. 

> vielleicht solle standarm. “keine KAtegorie” ausgewählt sein (als Kategorie). dann funktioniert die filterung etc. auch noch ohne große anpassungen

**Comment by skerbis** [comment]
Evtl. die erste Kategorie auswählen, wenn nur eine angelegt? 
Als Standard 'Keine Kategorie' zu wählen, empfinde ich nicht als sehr strukturiert.

**Comment by olien** [comment]
Kann man machen...
Und wenn es mehr als eine Kategorie sind wird es halt ein Pflichtfeld
